### ISSUE TITLE
Site login blocked after an expired session

### ISSUE THREAD

**Issue by Whoeaaah** [Ariadne-CMS/ariadne#20]
Hi,

The #12 issue has been fixed, but there is similar case which still persists:

After an expired session you can't login again untill you've cleared cookies or basicly closed the browser and visit the website from a cleanly. The symptoms are exactly the same.

GL
B.

**Comment by poef** [comment]
I've got a patch that should fix these issues. I've pasted it below:

---

diff --git a/lib/includes/loader.web.auth.php b/lib/includes/loader.web.auth.php
index f733e26..6669058 100644
--- a/lib/includes/loader.web.auth.php
+++ b/lib/includes/loader.web.auth.php
@@ -56,15 +56,10 @@
 						if ($data['timestamp']<(time()-86400)) {
 							// but do kill it if it's older than one day
 							unset($cookies[$sessionid]);
-							setcookie("ARSessionCookie[".$sessionid."]",null);
+							setcookie("ARSessionCookie[".$sessionid."]",false);
 						}
 					}
 				}
-			} else {
-				// only 1 cookie allowed, unset all cookies
-				if( $sessionid != $ARCurrent->session->id) {
-					setcookie("ARSessionCookie[".$sessionid."]",null,0,'/',false,$https,true);
-				}
 			}
 		}
 
@@ -79,6 +74,7 @@
 			$cookiename = "ARSessionCookie[".$ARCurrent->session->id."]";
 
 			header('P3P: CP="NOI CUR OUR"');
+			setcookie('ARCurrentSession', $ARCurrent->session->id, 0, '/', false, $https, true);
 			setcookie($cookiename,$cookie, 0, '/', false, $https, true);
 		}
 	}
diff --git a/lib/includes/loader.web.php b/lib/includes/loader.web.php
index 2e22acb..ec24515 100644
--- a/lib/includes/loader.web.php
+++ b/lib/includes/loader.web.php
@@ -277,17 +277,14 @@
 		if ($AR->hideSessionIDfromURL) {
 			$cookies = (array) ldGetCredentials();
 			$https = ($_SERVER['HTTPS']=='on');
-			if( ! isset($cookies[$ARCurrent->session->id])  && $ARCurrent->session->id != 0) {
-				foreach($cookies as $sessionid => $data){
-					// kill all other sessions
-					setcookie("ARSessionCookie[".$sessionid."]",null,0,'/', false, $https, true);
-				}
+			if( !isset($cookies[$ARCurrent->session->id])  && $ARCurrent->session->id !== 0) {
 				$data = array();
 				$data['timestamp']=time();
 				$cookie=ldEncodeCookie($data);
 				$cookiename = "ARSessionCookie[".$ARCurrent->session->id."]";
 				debug("setting cookie (".$ARCurrent->session->id.")(".$cookie.")");
 				header('P3P: CP="NOI CUR OUR"');
+				setcookie('ARCurrentSession', $ARCurrent->session->id, 0, '/', false, $https, true);
 				setcookie($cookiename,$cookie, 0, '/', false, $https, true);
 			}
 		}
@@ -302,6 +299,10 @@
 		ldSetSession($ARCurrent->session->id);
 	}
 
+	function ldGetCookieSession() {
+		return $_COOKIE['ARCurrentSession'];
+	}
+
 	function ldSetCache($file, $time, $image, $headers) {
 	global $store;
 
@@ -370,7 +371,7 @@
 	function ldGetUserCookie($cookiename="ARUserCookie") {
 		$cookie = false;
 
-		if( $_COOKIE[$cookiename] && !($cookiename == "ARSessionCookie")) {
+		if( $_COOKIE[$cookiename] && !($cookiename == "ARSessionCookie") && !($cookiename == 'ARCurrentSession') ) {
 			$ARUserCookie = $_COOKIE[$cookiename];
 			debug("ldGetUserCookie() = $ARUserCookie","object");
 			$cookie = json_decode($ARUserCookie,true);
@@ -389,9 +390,13 @@
 	function ldSetUserCookie($cookie, $cookiename="ARUserCookie", $expire=0, $path="/", $domain="", $secure=0, $consentneeded=false) {
 		$result = false;
 
+		if (substr($cookiename, 0, strlen('ARSessionCookie'))=='ARSessionCookie' || $cookiename=='ARCurrentSession' ) {
+			return false;
+		}
+
 		$cookieconsent = ldGetUserCookie("ARCookieConsent");
 		if (!$consentneeded || ($cookieconsent == true)) { // Only set cookies when consent has been given, or no consent is needed for this cookie.
-			if( $cookiename != "ARSessionCookie") {
+			if( $cookiename != "ARSessionCookie" && $cookiename != "ARCurrentSession" ) {
 				$ARUserCookie=json_encode($cookie);
 				debug("ldSetUserCookie(".$ARUserCookie.")","object");
 				header('P3P: CP="NOI CUR OUR"');
diff --git a/lib/modules/mod_auth/default.php b/lib/modules/mod_auth/default.php
index d7d9d99..c0dc233 100644
--- a/lib/modules/mod_auth/default.php
+++ b/lib/modules/mod_auth/default.php
@@ -189,7 +189,7 @@
 						} else {
 							debug("checkLogin: could not login ($login) on private session (".$ARCurrent->session->id.") with credentials from cookie: removing cookie", "all");
 							// FIXME: only the loader should know about cookies for sessions
-							setcookie("ARSessionCookie[".$ARCurrent->session->id."]", null);
+							setcookie("ARSessionCookie[".$ARCurrent->session->id."]", false);
 							$this->getUser('public');
 							$result = LD_ERR_ACCESS;
 						}
diff --git a/www/loader.php b/www/loader.php
index 314dc34..9fc2799 100644
--- a/www/loader.php
+++ b/www/loader.php
@@ -103,9 +103,10 @@
 			$AR_PATH_INFO=substr($AR_PATH_INFO,strlen($matches[0])-1);
 			$AR->hideSessionIDfromURL=false;
 		} elseif ($AR->hideSessionIDfromURL) {
-			$cookies = ldGetCredentials();
-			if (is_array($cookies) && count($cookies) === 1) {
-				$session_id=current(array_keys($cookies));
+			$cookies = (array) ldGetCredentials();
+			$current = ldGetCookieSession();
+			if ( array_key_exists( $current, $cookies ) ) {
+				$session_id = $current;
 			}
 		}
 
---

The problem seems to have been that cookies were incorrectly cleared and that the check if you need to set a cookie was done in $_COOKIE, which could contain the incorrectly cleared cookie. So no new cookie was sent. To prevent any possibility of that happening, I've rewritten the code to only clear cookies that are clearly old and no longer usefull. All session information is stored only in session cookies, so after closing the browser they will be gone anyway. To select which session is actively in use now, I added the 'ARCurrentSession' cookie. This selects which of the session cookies will be used in this request.

On our setup this fixed the problem with logging in. It should also fix any problems with manually started session using startsession(). Please let me know if this works for you as well.
