### ISSUE TITLE
FTP loader issue

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#81]
Some php/pinp errors don't respond as should. I attached an template which I used for testing. It has two lines with buggy code and the logs it generates. the GH: are extra logging I added.

To make sure it's not an client issue I also tested in two different clients. My usual WebDrive and the Npp FTP plugin in Notepad++

As you can see in case of the "bad" bug, the response with the error isn't send back to the ftp client and as such the client just waits to timeout. Very frustrating. Not a new error btw, but today I made time to see if I could sort things out.

Both bugs follow the same path through the ftp loader.php (the GH: lines with  line-number 858 is where it's called) and even with a "fixed" errormessage the issue remains. The $end for example is not the problem.  As far as I can tell all the filepointers (in the ftp loader) are decently closed, 

So I assume for now that it's deeper in the system. Maybe an issue in the pinp compiler or smt alike.

Testing template:
[pobject.test.any.txt](https://github.com/Ariadne-CMS/ariadne/files/45723/pobject.test.any.txt)

**Comment by poef** [comment]
The problem is that in some cases the PINP parser itself complains and then the FTP loader will send the error. In other cases the PHP parser itself fails. Somehow this error does get caught in the PHP SAPI client, but not in the CLI client the FTP server uses.
We've added a PHP parser written in PHP (nikic/php-parser) to check the code instead. This seems to fix the problem. We're testing it now, expect an update in Ariadne later today.
